### ISSUE TITLE
Android Emulator Support

### ISSUE THREAD

**Issue by ricbermo** [dimaportenko/telescope-simulators.nvim#2]
Hi, react-native developer here 😅 

just in case u wanna add support for launching android emulators, here you have a set of commands I use to list and launch emulators w/o opening Android Studio.

1. `emulator -list-avds`
2. `emulator -avd <id_you_get_from_prev_command>`

Cheers.

**Comment by dimaportenko** [comment]
Hi @ricbermo,
this is exactly what I wanted to do next :) Btw. I'm an RN developer as well.

**Comment by dimaportenko** [comment]
@ricbermo done, use setup config to enable android emulators
```lua
require("simulators").setup({
  android_emulator = false,
  apple_simulator = true,
})
```
