### ISSUE TITLE
LunarVim

### ISSUE THREAD

**Issue by Burnsedia** [dimaportenko/telescope-simulators.nvim#6]
Could this work with LunarVim, It should.

**Comment by dimaportenko** [comment]
@Burnsedia I don't use LunarVim, but I believe it shouldn't be an issue to use it there. Do you have any particular issues with it?

**Comment by Burnsedia** [comment]
I am setting up a LunarVim course for new Neovim users.

**Comment by Burnsedia** [comment]
I wanted to have the for my mobile development modale

**Comment by dimaportenko** [comment]
Cool, let me know if you have any issues.

**Comment by Burnsedia** [comment]
It seems to work well, Thanks for your work. Are you looking for maintainers and contributers.  I am learning Lua as we speak to maintain this.

**Comment by dimaportenko** [comment]
@Burnsedia sure, feel free to contribute.

**Comment by Burnsedia** [comment]
@dimaportenko It doesn't work on my Linux box, The IOS Simulator needs to be an optional dependent like the Android emulator. This will allow Windows and Linux users as well.
