### ISSUE TITLE
emulator doesn't show in Linux 

### ISSUE THREAD

**Issue by lsao2000** [dimaportenko/telescope-simulators.nvim#8]
I have added all the configurations and I didn't encounter any error but when I run the command ```Telescope simulators run``` nothing happens

**Comment by dimaportenko** [comment]
This plugin based on the output of following command
```bash
xcrun simctl list devices available
```
what do you see when you run it?

**Comment by dimaportenko** [comment]
duplicated https://github.com/dimaportenko/telescope-simulators.nvim/issues/7

**Comment by lsao2000** [comment]
i get an error

Le dim. 25 févr. 2024 à 16:44, Dima Portenko ***@***.***> a
écrit :

**Comment by dimaportenko** [comment]
Sorry, I didn’t read carefully your issue. My comment related to the iOS simulator on Mac OS. Regarding Linux you can check discussion https://github.com/dimaportenko/telescope-simulators.nvim/issues/7
